version: '3.4'

services:
  frontend:
    env_file:
      - src/.env
    image: frontend
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000

  backend:
    env_file:
      - src/.env
    image: backend
    build:
      context: ./src
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
