version: '3.4'

services:
  frontend:
    env_file:
      - frontend/.env
    image: moneyroundup_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 80:80

  backend:
    env_file:
      - src/.env
    image: moneyroundup_backend
    build:
      context: ./src
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    restart: on-failure
