version: '3.4'

services:
  moneyroundup:
    image: moneyroundup
    build:
      context: ./src
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    volumes:
      - /src/moneyroundup
  frontend:
    image: frontend
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
