version: '3.4'

services:
  frontend:
    env_file:
      - src/.env
    image: frontend
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    volumes:
      - /Users/sosaedison/Documents/GitHub/money-roundup/frontend:/app/frontend

  backend:
    image: sosalosa/moneyroundup_backend
    # build:
    #   context: ./src
    #   dockerfile: ./Dockerfile
    ports:
      - 80:80
    restart: on-failure
