version: '3.4'

services:
  frontend:
    image: sosalosa/moneyroundup_frontend:latest
    ports:
      - 8080:80
    restart: on-failure

  backend:
    image: sosalosa/moneyroundup_backend:latest
    ports:
      - 8000:8000
    restart: on-failure
